In [2]:
#Numpy is Fundamental Library for scientific computing in Python
#It supports arrays and matrices operartions
import numpy as np


In [ ]:
#create arrays using numpy
#1-D array

arr1 = np.array([1,2,'hi'])
print("Single Dimensional array with "+str(len(arr1))+" elements")
print(arr1)
print(type(arr1))
print(arr1.shape)

In [ ]:
#even we can reshape array with reshape function
#2D array
arr1.reshape(1,3)  #1 Row, 3 columns
print("arr1",end=" : ")
print(arr1)
print(arr1.shape)
print()
arr2 = arr1.reshape(1,3)
print("arr2(2-D array)",end=" : ")
print(arr2)
print(arr2.shape)

In [3]:
#2d array
arr3 = np.array([[1,3,4,4,2],[2,4,2,2,1]])
print(arr3)
print(arr3.shape)

[[1 3 4 4 2]
 [2 4 2 2 1]]
(2, 5)


In [ ]:
#reshaping 2 D array
arr4 = arr3.reshape(5,2)
print(arr4)
print(arr4.shape)

In [ ]:
#Array creation with inbuilt functions
ar5 = np.arange(0,11,2)
ar6 = ar5.reshape(2,3)
print("ar5 : ",end=" ")
print(ar5)
print(ar5.shape)
print("ar5 : ",end=" ")
print(ar6)
print(ar6.shape)

In [ ]:
#ones
ar7 = np.ones((3,5))
print(ar7)

In [ ]:
#identity Matrix
ar8 = np.eye(3)
print(ar8)

In [ ]:
#Attributes of numpy array

arr = np.array([[4,3,2],[1,2,3]])
print("arr : \n", arr)
print("Shape : ",arr.shape)
print("Number of dimensions : ",arr.ndim)
print("Size(Number of elements) : ",arr.size)
print("Data type : ",arr.dtype) #depends on the array initiation
print("Item Size (in bytes) : ",arr.itemsize) #depends on the array initiation and written data type

In [6]:
a1 = [1,2,3,4]
a2 = [2,3,4,5]

#Addition of lists
print(a1+a2)

#numpy vectorized operations
ar1 = np.array([2,3,1,4])
ar2 = np.array([5,4,2,3])

#Element wise addition
print("Addition : ",ar1+ar2)


#Element wise substraction
print("substraction : ",ar1-ar2)


#Element wise multiplication
print("multiplication : ",ar1*ar2)


#Element wise division
print("division : ",ar1/ar2)

[1, 2, 3, 4, 2, 3, 4, 5]
Addition :  [7 7 3 7]
substraction :  [-3 -1 -1  1]
multiplication :  [10 12  2 12]
division :  [0.4        0.75       0.5        1.33333333]


In [7]:
#Universal Functions 

arr32 = np.array([1,3,2,5,6])

#Square root
print(np.sqrt(arr32))

#Exponent
print(np.exp(arr32))

#Sine
print(np.sin(arr32))

#log
print(np.log(arr32))

[1.         1.73205081 1.41421356 2.23606798 2.44948974]
[  2.71828183  20.08553692   7.3890561  148.4131591  403.42879349]
[ 0.84147098  0.14112001  0.90929743 -0.95892427 -0.2794155 ]
[0.         1.09861229 0.69314718 1.60943791 1.79175947]


In [9]:
#Array Slicling and indexing
arr = np.array([[1,2,3,4,2],[9,2,3,4,5],[3,4,5,2,5]])

print("Arr : \n",arr)


Arr : 
 [[1 2 3 4 2]
 [9 2 3 4 5]
 [3 4 5 2 5]]


In [19]:
#Accessing elements from the above array
print("First row : ",arr[0])
print("First row First Column",arr[0][0])
print("third row second column",arr[2][1])
print("Elements in second row and third row until 4th column")
print(arr[1:,2:4])
print()
print("Elements in first row and second row last two column")
print(arr[0:2,3:])

First row :  [1 2 3 4 2]
First row First Column 1
third row second column 4
Elements in second row and third row until 4th column
[[3 4]
 [5 2]]

Elements in first row and second row last two column
[[4 2]
 [4 5]]


In [24]:
#Modifying array elements
arr[0][1] = 2190
print(arr)

[[   1 2190    3    4    2]
 [   9    2    3    4    5]
 [   3    4    5    2    5]]


In [27]:
arr[1:2,2:] = 8931
print(arr)

[[   1 2190    3    4    2]
 [   9    2 8931 8931 8931]
 [   3    4    5    2    5]]


In [30]:
#stasticial concept

#Normalization 
#We need to change the data such that, mean is zero and standard deviation as 1

data = np.array([1,2,3,4,2,1,4,7,8,5,9])

mean_ = np.mean(data)
print(mean_)

median_ = np.median(data)
print(median_)

stdDvtn = np.std(data)
print(stdDvtn)

variance_ = np.var(data)
print(variance_)


#NOrmalization
normalized_Data = (data-mean_)/stdDvtn
print("Normalized Data : ",normalized_Data)

4.181818181818182
4.0
2.6566616720368104
7.0578512396694215
Normalized Data :  [-1.19767534 -0.82126309 -0.44485084 -0.06843859 -0.82126309 -1.19767534
 -0.06843859  1.06079816  1.43721041  0.30797366  1.81362266]


In [40]:
#Logical Operations
data1 = np.array([10,2,3,4,5,6,7,9,10,2,23])
print(data1>5)
print(data1[data1>5])

[ True False False False False  True  True  True  True False  True]
[10  6  7  9 10 23]


29023